version: "3.8"
services:
  elasticsearch:
    image: isclab/elk:latest
    restart: always
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d:ro
      - elk:/var/lib/elasticsearch
    ports:
    - "9200:9200"
    - "5601:5601"
    - "5144:5144"
volumes:
  elk:
